# Site settings
title: Personal Website
description: Explore Mike's world of ICT web programming expertise and experience. From technical prowess to professional journey, discover it all here.
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Mike Ye
user_description: I am a passionate IT enthusiast with a keen interest in web development. Currently pursuing graduate studies, I am dedicated to exploring the dynamic intersection of technology and creativity. Eager to contribute innovative solutions to the ever-evolving digital landscape.
user_title: Software Engineer
email: xye804@aucklanduni.ac.nz
# twitter_username: lorem_ipsum
instagram_username: Maoxiao Ye
facebook_username: Maoxiao Ye
linkedin_username: Maoxiao Ye
github_username: xye804
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ["package.json", "src", "node_modules", "vendor"]
